apiVersion: v1
kind: Service
metadata:
  name: udacity-capstone-project5
  namespace: udacity-capstone-project5
  labels:
    app: udacity-capstone-project5
spec:
  selector:
    app: udacity-capstone-project5
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80