apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-capstone-project5
  namespace: udacity-capstone-project5
  labels:
    app: udacity-capstone-project5
spec:
  replicas: 3
  selector:
    matchLabels:
      app: udacity-capstone-project5
  # strategy:
  #   type: RollingUpdate
  #   rollingUpdate:
  #     maxUnavailable: 50%
  #     maxSurge: 1
  template:
    metadata:
      labels:
        app: udacity-capstone-project5
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: nginx
        image: tiennguyen77/udacity-caption-project-devops
        ports:
        - name: http
          containerPort: 80
        imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux
